remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Data Engineering & Analysis Portfolio
description: Showcasing my projects in data engineering, analysis, and visualization
show_downloads: false
